name: Action Update Changelog
description: Updates changelog based on git commits
author: KrogerWalt
inputs:
  changelog_file:
    description: Overrides the path to the changelog.
    required: false
    default: "CHANGELOG.md"
  branch_name:
    description: If provided, will be used instead of current branch name to create message.
    required: false
  ticket_url_prefix:
    description: If provided, will be used to create a link for referenced issues.
    required: false
  version:
    description: The version of the release will be added above this and the other unreleased changes. If not supplied this change will be added to unreleased changes.
    required: false
outputs:
  change_md:
    description: The Markdown that was generated for this change.
runs:
  using: docker
  image: Dockerfile
branding:
  icon: list
  color: purple
