name: On PR Merge

on:
  workflow_dispatch:
  pull_request:
    types: [closed]
    branches: [main]

jobs:
  Update-Changelog:
    if: ${{ github.event.pull_request.merged }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: KrogerWalt/action-get-latest-tag@v2
        id: get-latest-tag

      - uses: KrogerWalt/action-update-changelog@main
        id: changelog-update
        with:
          branch_name: ${{ github.event.pull_request.head.ref }}
          ticket_url_prefix: https://github.com/${{ github.repository }}/issues/
          version: ${{ steps.get-latest-tag.outputs.tag }}

      - name: Commit Changelog
        run: |
          git config --global --replace-all user.name "$GITHUB_ACTOR"
          git config --global --replace-all user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git add CHANGELOG.md
          git commit -m "Updating Changelog"
          git push origin main
