name: Test Changelog

on:
  workflow_dispatch:


jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: KrogerWalt/action-get-latest-tag@v2
        id: get-latest-tag
        if: ${{ steps.release-label.outputs.level != null }}

      - uses: actions-ecosystem/action-bump-semver@v1
        id: bump-semver
        if: ${{ steps.release-label.outputs.level != null }}
        with:
          current_version: ${{ steps.get-latest-tag.outputs.tag }}
          level: ${{ steps.release-label.outputs.level }}

      #      - name: print-changelog
      #        run: cat CHANGELOG.md

      - uses: KrogerWalt/action-update-changelog@main
        id: changelog-update
        if: ${{ github.event.pull_request.merged == true }}
        with:
          ticket_url_prefix: https://github.com/${{ github.repository }}/issues/
          version: ${{ steps.bump-semver.outputs.new_version }}

#      - name: print-changedlog
#        run: cat CHANGELOG.md

      - run: echo "${{ steps.changelog-update.outputs.change_md }}"
