name: Test Changelog

on:
  workflow_dispatch:


jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: KrogerWalt/action-get-latest-tag@v2
        id: get-latest-tag

      - uses: actions-ecosystem/action-bump-semver@v1
        id: bump-semver
        with:
          current_version: ${{ steps.get-latest-tag.outputs.tag }}
          level: 'patch'

      - uses: KrogerWalt/action-update-changelog@main
        id: changelog-update
        with:
          ticket_url_prefix: https://github.com/${{ github.repository }}/issues/
          version: ${{ steps.get-latest-tag.outputs.tag }}

      - name: print-changedlog
        run: cat CHANGELOG.md

      - run: echo "${{ steps.changelog-update.outputs.change_md }}"
